---
title: "FlexDashboard, Siny, and RHandsontable -- Combined!"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(rhandsontable)

outdir = getwd()
outfilename="gradebook1"

  DF = readRDS("gradebook1.rds")
if("gradebook1.rds" %in% list.files(outdir)){
}else{
  DF <- data.frame(
  Student = c("Andile", "Andile", "Bongani", "Bongani", "Charlie"),
  Teacher = c("Brendan", "David", "Brendan", "David", "Brendan"),
  Grade = integer(5),
  Comment = character(5))
}


```


Column {.sidebar}
-----------------------------------------------------------------------

Shiny app grade book based on an example given in the rhandsontable package.
Note the following table features:

 - Editing prohibited for name and teacher
 
 - Adding/deleting rows & columns prohibited
 
 - Conditional highlighting if grade values are silly
 
 - Right click to export to .csv


Column
-----------------------------------------------------------------------

##### This is still flexdashboard

```{r}
shinyApp(
  ui <- shinyUI(fluidPage(
      h5("This is Shiny"),
      actionButton("save", " Save Grades ", icon("save")),
      br(),
      br(),
      rHandsontableOutput("hot")
    )
  ),
  server <- shinyServer(function(input, output) {
    
    values <- reactiveValues()
    
    ## Handsontable
    observe({
      if (!is.null(input$hot)) {
        DF = hot_to_r(input$hot)
      } else {
        if (is.null(values[["DF"]]))
          DF <- DF
        else
          DF <- values[["DF"]]
      }
      values[["DF"]] <- DF
    })
    
    output$hot <- renderRHandsontable({
      DF <- values[["DF"]]
      if (!is.null(DF))
        rhandsontable(DF, useTypes = TRUE, stretchH = "all") %>%
        #DF[Position == "Long", `:=`(Weight = Weight / sum(Weight) * 1.3)]
        hot_col(c("Student", "Teacher"), readOnly = TRUE) %>%
        hot_col("Comment", allowInvalid = TRUE) %>%
        #hot_validate_numeric("Grade", min = 0, max = 100) %>%
        hot_table(highlightCol = TRUE, highlightRow = TRUE) %>%
        hot_cols(columnSorting = TRUE) %>%
        hot_cols(renderer = "
         function (instance, td, row, col, prop, value, cellProperties) {
           Handsontable.renderers.NumericRenderer.apply(this, arguments);
           if (value > 100) {
            td.style.background = 'red';
           } else if (value < 0) {
            td.style.background = 'red';
           }
         }") %>%
        hot_context_menu(
          allowRowEdit = FALSE, 
          allowColEdit = FALSE,
          customOpts = list(
            csv = list(name = "Download to CSV",
                          callback = htmlwidgets::JS(
                            "function (key, options) {
                               var csv = csvString(this, sep=',', dec='.');
      
                               var link = document.createElement('a');
                               link.setAttribute('href', 'data:text/plain;charset=utf-8,' +
                                 encodeURIComponent(csv));
                               link.setAttribute('download', 'data.csv');
                               document.body.appendChild(link);
                               link.click();
                               document.body.removeChild(link);
                             }"))))
    })
    
    #SAVE
    observeEvent(input$save, {
      finalDF <- isolate(values[["DF"]])
      saveRDS(finalDF, file=file.path(outdir, sprintf("%s.rds", outfilename)))
    })
  })
  #,
  #options = list(height = 600)
)
```
